### ISSUE TITLE
 talisman 1.11.0 error with Yatopia(17) server

### ISSUE THREAD

**Issue by Redo11** [Auxilor/Talismans#1]
selfcompiled talisman on Yatopia, continuation of EcoEnchants errors, the saga continues.

[16:21:34 INFO]: [Talismans] Enabling Talismans v1.11.0
[16:21:34 INFO]: [Talismans] 
[16:21:34 INFO]: [Talismans] Loading Talismans
[16:21:34 INFO]: [Talismans] Loaded integrations: 
[16:21:34 ERROR]: Error occurred while enabling Talismans v1.11.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/willfp/talismans/proxy/proxies/SkullProxy
        at com.willfp.talismans.display.TalismanDisplay.displayTalisman(TalismanDisplay.java:90) ~[?:?]
        at com.willfp.talismans.talismans.Talisman.update(Talisman.java:207) ~[?:?]
        at com.willfp.talismans.talismans.Talisman.<init>(Talisman.java:175) ~[?:?]
        at com.willfp.talismans.talismans.talismans.ZombieTalisman.<init>(ZombieTalisman.java:16) ~[?:?]
        at com.willfp.talismans.talismans.Talismans.<clinit>(Talismans.java:52) ~[?:?]
        at com.willfp.talismans.commands.TabcompleterTalgive.<clinit>(TabcompleterTalgive.java:24) ~[?:?]
        at com.willfp.talismans.commands.CommandTalgive.getTab(CommandTalgive.java:28) ~[?:?]
        at com.willfp.eco.util.command.AbstractCommand.register(AbstractCommand.java:139) ~[?:?]
        at java.util.Arrays$ArrayList.forEach(Arrays.java:4390) ~[?:?]
        at com.willfp.eco.util.plugin.AbstractEcoPlugin.onEnable(AbstractEcoPlugin.java:263) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Yatopia-17]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[server.jar:git-Yatopia-17]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[server.jar:git-Yatopia-17]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[server.jar:git-Yatopia-17]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[server.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:227) ~[server.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[server.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[server.jar:git-Yatopia-17]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.willfp.talismans.proxy.proxies.SkullProxy
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[server.jar:git-Yatopia-17]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[server.jar:git-Yatopia-17]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 19 more
[16:21:34 INFO]: [Talismans] Disabling Talismans v1.11.0

**Comment by Auxilor** [comment]
Discord for support
