### ISSUE TITLE
InvocationTargetException / LinkageError

### ISSUE THREAD

**Issue by marcelschoen** [Auxilor/Talismans#40]
Version 5.126.0 of the plugin gives me these exceptions in the server console log (Paper 1.19.2) on startup:

```
[23:03:49 INFO]: [eco] Loaded eco
[23:03:49 WARN]: java.lang.reflect.InvocationTargetException
[23:03:49 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:03:49 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:03:49 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:03:49 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[23:03:49 WARN]: 	at eco-6.44.1-all.jar//com.willfp.eco.internal.config.EcoConfigHandler.callUpdate(EcoConfigHandler.kt:25)
[23:03:49 WARN]: 	at eco-6.44.1-all.jar//com.willfp.eco.core.EcoPlugin.reload(EcoPlugin.java:563)
[23:03:49 WARN]: 	at eco-6.44.1-all.jar//com.willfp.eco.core.EcoPlugin.afterLoad(EcoPlugin.java:538)
[23:03:49 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:03:49 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:03:49 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1114)
[23:03:49 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[23:03:49 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[23:03:49 WARN]: Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'com.willfp.eco.core.gui.menu.Menu com.willfp.eco.core.gui.GUIHelperExtensions.menu(int, kotlin.jvm.functions.Function1)' the class loader 'Talismans v5.126.0.jar' @67978176 of the current class, com/willfp/talismans/bag/TalismanBag, and the class loader 'eco-6.44.1-all.jar' @761e2cf1 for the method's defining class, com/willfp/eco/core/gui/GUIHelperExtensions, have different Class objects for the type kotlin/jvm/functions/Function1 used in the signature (com.willfp.talismans.bag.TalismanBag is in unnamed module of loader 'Talismans v5.126.0.jar' @67978176, parent loader java.net.URLClassLoader @4445629; com.willfp.eco.core.gui.GUIHelperExtensions is in unnamed module of loader 'eco-6.44.1-all.jar' @761e2cf1, parent loader java.net.URLClassLoader @4445629)
[23:03:49 WARN]: 	at Talismans v5.126.0.jar//com.willfp.talismans.bag.TalismanBag.update(TalismanBag.kt:63)
[23:03:49 WARN]: 	... 12 more
``

**Comment by Marotheit** [comment]
I am also having this error.
